"""Parity suite: the Python port must reproduce the REAL FairHouse TypeScript
byte-for-byte. reference.json is generated by tools/gen_reference.ts running the
actual casino code; every value below is checked against Python's output.

Regenerate the fixture with:
    npx tsx math-lab/tools/gen_reference.ts > math-lab/tests/reference.json
"""
import json
from pathlib import Path

import pytest

from fairhouse import games as g
from fairhouse.provably_fair import bet_hmac, float_from_hex, sha256_hex

REF = json.loads((Path(__file__).parent / "reference.json").read_text())
SERVER, CLIENT = REF["server"], REF["client"]


@pytest.mark.parametrize("bet", REF["bets"], ids=lambda b: f"nonce{b['nonce']}")
def test_bet_parity(bet):
    hmac = bet_hmac(SERVER, CLIENT, bet["nonce"])
    assert hmac == bet["hmac"], "HMAC-SHA256 digest mismatch"
    assert float_from_hex(hmac) == bet["floatFromHex"]
    assert g.dice_roll(hmac) == bet["diceRoll"]
    assert g.coin_result(hmac) == bet["coin"]
    assert g.limbo_result(hmac) == bet["limbo"]
    assert g.roulette_number(hmac) == bet["rouletteNumber"]
    assert g.roulette_color(g.roulette_number(hmac)) == bet["rouletteColor"]
    assert g.wheel_segment(hmac) == bet["wheelSegment"]
    assert g.wheel_multiplier(g.wheel_segment(hmac)) == bet["wheelMultiplier"]
    assert g.slot_spin(hmac) == bet["slotSpin"]
    assert g.slot_payout(g.slot_spin(hmac)) == bet["slotPayout"]
    assert g.plinko_path(hmac) == bet["plinkoPath"]
    assert g.plinko_bucket(g.plinko_path(hmac)) == bet["plinkoBucket"]
    assert g.plinko_multiplier(g.plinko_bucket(g.plinko_path(hmac))) == bet["plinkoMultiplier"]
    # order-sensitive hash-sort deals — the strictest parity check
    assert g.mines_layout(hmac, 3) == bet["minesLayout3"]
    assert g.tower_layout(hmac, 4, 1, 9) == bet["towerEasy"]
    assert g.tower_layout(hmac, 3, 2, 9) == bet["towerExpert"]
    assert g.keno_draw(hmac) == bet["kenoDraw"]
    assert g.shuffled_deck(hmac)[:10] == bet["deckFirst10"]


def test_scalars():
    s = REF["scalars"]
    assert sha256_hex("sample-123") == s["sha256_sample"]
    for target, mult in s["diceMultiplier"]:
        assert g.dice_multiplier(target) == mult
    assert g.COIN_MULTIPLIER == s["coinMultiplier"]
    for revealed, mines, mult in s["minesMultiplier"]:
        assert g.mines_multiplier(revealed, mines) == mult
    for diff, mult in s["towerMultiplier"]:
        assert g.tower_multiplier(diff, 9) == mult
    for spots, hits, mult in s["kenoMultiplier"]:
        assert g.keno_multiplier(spots, hits) == mult
    for rank, mult in s["hiloHigher"]:
        assert g.hilo_higher_mult(rank) == mult
    for rank, mult in s["hiloLower"]:
        assert g.hilo_lower_mult(rank) == mult
    for hand, result in s["poker"]:
        assert g.poker_evaluate(hand)["multiplier"] == result["multiplier"]
    for hand, value in s["handValue"]:
        assert g.hand_value(hand) == value
