// Build public/icons.js by inlining real Lucide SVGs (CSP-safe — no CDN at runtime).
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const SRC = join(here, "..", "node_modules", "lucide-static", "icons");

// icon name (ours) -> lucide file
const FILES = {
  dices: "dices", coins: "coins", rocket: "rocket", bomb: "bomb", castle: "castle",
  triangle: "triangle", target: "target", "disc-3": "disc-3", "grid-3x3": "grid-3x3",
  brain: "brain", cherry: "cherry", "arrow-up-down": "arrow-up-down", club: "club",
  spade: "spade", trophy: "trophy", palette: "palette", "volume-2": "volume-2",
  "volume-x": "volume-x", "shield-check": "shield-check", wallet: "wallet", house: "house",
};

const inner = (svg) => svg.replace(/^[\s\S]*?<svg[^>]*>/, "").replace(/<\/svg>[\s\S]*$/, "").replace(/\s+/g, " ").trim();

const P = {};
for (const [name, file] of Object.entries(FILES)) {
  P[name] = inner(readFileSync(join(SRC, `${file}.svg`), "utf8"));
}

const out = `// Auto-generated by scripts/build-icons.mjs — inline Lucide SVGs (CSP-safe).
const P = ${JSON.stringify(P, null, 0)};

export function icon(name, { size = 24, cls = "" } = {}) {
  return \`<svg class="ico \${cls}" width="\${size}" height="\${size}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">\${P[name] || ""}</svg>\`;
}

// Game key -> Lucide icon name
export const GAME_ICON = {
  dice: "dices", coinflip: "coins", crash: "rocket", mines: "bomb", tower: "castle",
  plinko: "triangle", roulette: "target", wheel: "disc-3", keno: "grid-3x3", memory: "brain",
  slots: "cherry", hilo: "arrow-up-down", vpoker: "club", blackjack: "spade",
};
export const gameIcon = (key, opts) => icon(GAME_ICON[key] || "dices", opts);
`;

writeFileSync(join(here, "..", "public", "icons.js"), out);
console.log(`Wrote public/icons.js with ${Object.keys(P).length} icons.`);
